bucket_name = "ta-terraform-tfstates-686520628199"                              #should be changed with "ring-challenge -<account no.>"
owner_name = "Klesta"
path_to_triggerLambda = "${path.module}/ring_no_challenge/trigger.py"
path_path_to_output = "${path.module}/files/hello.zip"
forward_account_id = "1234567"
donor_account_id = "1234567"